"""Content / Template Agent.

Turns a `product_ideas` row into an actual file on disk and registers it in
`products`. No LLM is configured yet (see ROADMAP.md), so every generator
here is deterministic and template-based rather than free-text generation -
each one is chosen because it can be genuinely useful without creative
writing:

  - calculator  -> a real, working single-file HTML/JS tool
  - checklist   -> a structured Markdown checklist (generic best-practice
                   phases, not a specific claim about any market)
  - template    -> an actual CSV template with sensible columns/sample rows
  - prompt_pack -> a set of concrete, ready-to-use AI prompts

`ebook` and `sop` formats need real written prose to be worth anything, and
that's exactly what a template can't honestly provide - so those are built
as a reviewable outline/skeleton only, and left at status='draft' rather
than 'ready', so nothing downstream mistakes a skeleton for a finished
product.
"""
import csv
import io
import sys
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agents.common import SITE_CSS, now_iso, slugify
from core.db import get_connection, init_db

OUT_DIR = Path(__file__).resolve().parent.parent / "data" / "exports" / "products"


def topic_label(term: str, generic_word: str, fallback: str) -> str:
    """Avoid degenerate content like a checklist literally titled 'checklist' -
    if the keyword IS the format word, use a sensible generic subject instead."""
    return fallback if term.strip().lower() == generic_word else term.title()


# ---------------------------------------------------------------------------
# Generators. Each returns (file_extension, content_string).
# ---------------------------------------------------------------------------

def generate_checklist(term: str) -> tuple[str, str]:
    topic = topic_label(term, "checklist", "Launching a New Digital Product")
    content = f"""# {topic} Checklist

A practical, repeatable checklist. Copy this into Notion, a PDF, or plain
text - it's designed to be used, not just read.

## 1. Before You Start
- [ ] Write down the single outcome that defines "done" for this
- [ ] Identify who this is for and what they already tried that didn't work
- [ ] Block time on your calendar - checklists don't execute themselves

## 2. Setup
- [ ] Gather the tools/accounts/access you'll need up front
- [ ] Remove one blocker that you know will interrupt you mid-task
- [ ] Set a realistic deadline and write it somewhere visible

## 3. Core Steps
- [ ] Do the smallest version first - get *a* version working end to end
- [ ] Get feedback before polishing
- [ ] Fix the one thing that feedback flagged most often

## 4. Quality Check
- [ ] Re-read/re-test as if you were seeing it for the first time
- [ ] Check it against the "done" definition from step 1
- [ ] Have one other person sanity-check it if possible

## 5. Common Mistakes to Avoid
- [ ] Don't add scope you didn't plan for in step 1
- [ ] Don't skip the feedback step to save time - it costs more later
- [ ] Don't ship without checking it once more against the original goal

---
Generated by the Biznis pipeline for topic: "{term}".
"""
    return "md", content


def generate_prompt_pack(term: str) -> tuple[str, str]:
    topic = topic_label(term, "prompt", "Your Topic")
    prompts = [
        ("Explainer", f"Explain {topic} to a complete beginner in 5 short "
                       f"paragraphs, using one concrete real-world analogy. "
                       f"Avoid jargon; define any term you must use."),
        ("Comparison", f"Compare the 3 most common approaches to {topic}. "
                       f"For each, give: what it's best for, its biggest "
                       f"limitation, and who should NOT use it."),
        ("Checklist request", f"Give me a step-by-step checklist for getting "
                       f"started with {topic} this week, assuming I have "
                       f"2 hours of focused time total."),
        ("Troubleshooting", f"I'm working on {topic} and hit this problem: "
                       f"[describe your problem here]. List the 5 most likely "
                       f"causes, ordered from most to least common."),
        ("Critique", f"Here is my current approach to {topic}: [paste your "
                       f"work here]. Critique it as a skeptical expert would - "
                       f"what's the single biggest weakness?"),
        ("Simplify", f"Take this explanation of {topic}: [paste text here]. "
                       f"Rewrite it so a smart 12-year-old would understand it, "
                       f"without losing the important nuance."),
        ("Decision help", f"I need to decide between these options for "
                       f"{topic}: [list your options]. Ask me the 3 questions "
                       f"you'd need answered before recommending one."),
        ("Plan", f"Turn {topic} into a 30-day plan with one concrete action "
                       f"per week. Assume I can spend 3 hours/week on it."),
        ("Risk check", f"What are the 3 most common ways people fail at "
                       f"{topic}, and what's the earliest warning sign of each?"),
        ("Summary", f"Summarize the current best practices for {topic} in "
                       f"under 150 words, written for someone who already "
                       f"knows the basics."),
    ]
    lines = [f"# {topic}: AI Prompt Pack", "",
             "10 ready-to-use prompts. Replace bracketed placeholders with "
             "your own details before sending.", ""]
    for i, (label, prompt) in enumerate(prompts, 1):
        lines += [f"## {i}. {label}", "", f"> {prompt}", ""]
    return "md", "\n".join(lines)


def generate_template_csv(term: str) -> tuple[str, str]:
    buf = io.StringIO()
    writer = csv.writer(buf)
    if "invoice" in term.lower():
        writer.writerow(["Invoice Number", "Issue Date", "Due Date", "Bill To",
                          "Item Description", "Quantity", "Unit Price", "Line Total"])
        writer.writerow(["INV-0001", "2026-07-26", "2026-08-09", "Client Name",
                          "Service or product description", 1, 100.00, 100.00])
        writer.writerow(["", "", "", "", "", "", "Subtotal", 100.00])
        writer.writerow(["", "", "", "", "", "", "Tax (0%)", 0.00])
        writer.writerow(["", "", "", "", "", "", "Total Due", 100.00])
    else:
        writer.writerow(["Date", "Category", "Description", "Amount", "Status", "Notes"])
        writer.writerow(["2026-07-26", "Example category", "Example item", 0.00, "Pending", ""])
    return "csv", buf.getvalue()


def generate_calculator_html(term: str) -> tuple[str, str]:
    topic = topic_label(term, "calculator", "Percentage & Markup")
    content = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{topic} Calculator</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
{SITE_CSS}
  label {{ display: block; margin-top: 1rem; font-size: 0.9rem; color: var(--text-muted); font-weight: 600; }}
  input {{ width: 100%; padding: 0.65rem 0.75rem; font-size: 1rem; margin-top: 0.35rem;
           box-sizing: border-box; color: var(--text); background: var(--bg);
           border: 1px solid var(--border); border-radius: 8px; }}
  .result b {{ font-size: 1.3rem; }}
</style>
</head>
<body>
<main>
<h1>{topic} Calculator</h1>
<div class="card">
<label>Base amount
  <input type="number" id="base" value="100" step="0.01">
</label>
<label>Percentage (%)
  <input type="number" id="pct" value="20" step="0.01">
</label>
</div>
<div class="card result">
  Percentage of base: <b id="pctOf">-</b><br>
  Base + percentage (markup): <b id="markupUp">-</b><br>
  Base - percentage (discount): <b id="markupDown">-</b>
</div>
</main>
<script>
  function recalc() {{
    const base = parseFloat(document.getElementById('base').value) || 0;
    const pct = parseFloat(document.getElementById('pct').value) || 0;
    const pctOf = base * (pct / 100);
    document.getElementById('pctOf').textContent = pctOf.toFixed(2);
    document.getElementById('markupUp').textContent = (base + pctOf).toFixed(2);
    document.getElementById('markupDown').textContent = (base - pctOf).toFixed(2);
  }}
  document.getElementById('base').addEventListener('input', recalc);
  document.getElementById('pct').addEventListener('input', recalc);
  recalc();
</script>
</body>
</html>
"""
    return "html", content


def generate_outline(term: str, format_hint: str) -> tuple[str, str]:
    topic = term.title()
    content = f"""# {topic}: Outline (DRAFT - needs full prose)

Status: skeleton only. This is a structural outline, not finished content.
An LLM (local via Ollama, or via an OpenRouter key) or a human writer still
needs to fill in the actual prose - see docs/ROADMAP.md.

## Working title
The Practical Guide to {topic}

## Target reader
Someone who has heard of "{term}" and needs a fast, practical orientation -
not an academic treatment.

## Section outline
1. Why {topic} matters right now (1 short paragraph, cite the concrete
   signal that surfaced this topic - see the `rationale` field on the
   product idea for the underlying keyword/demand score)
2. The 3 most common ways people approach {topic}
3. A step-by-step walkthrough of the simplest correct approach
4. Common mistakes and how to spot them early
5. A short checklist summarizing the above (link to the Checklist Agent
   output if one exists for a related keyword)
6. Where to go deeper (list 2-3 credible free resources - no invented links)

## Format notes
- Target length: 1500-2500 words for a lead-magnet-style ebook
- format_hint from product_agent: {format_hint}
"""
    return "md", content


GENERATORS = {
    "checklist": lambda term, fmt: generate_checklist(term),
    "prompt_pack": lambda term, fmt: generate_prompt_pack(term),
    "template": lambda term, fmt: generate_template_csv(term),
    "calculator": lambda term, fmt: generate_calculator_html(term),
    "ebook": lambda term, fmt: generate_outline(term, fmt),
    "sop": lambda term, fmt: generate_outline(term, fmt),
}
DRAFT_ONLY_FORMATS = {"ebook", "sop"}


def build_idea(idea_id: int) -> Optional[dict]:
    conn = get_connection()
    cur = conn.cursor()
    idea = cur.execute(
        """SELECT pi.id, pi.title, pi.format, pi.status, k.term
           FROM product_ideas pi JOIN keywords k ON k.id = pi.target_keyword_id
           WHERE pi.id = ?""",
        (idea_id,),
    ).fetchone()
    if not idea:
        conn.close()
        return None
    if idea["status"] not in ("proposed", "approved"):
        conn.close()
        return None

    generator = GENERATORS.get(idea["format"])
    if not generator:
        conn.close()
        return None

    ext, content = generator(idea["term"], idea["format"])
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    file_path = OUT_DIR / f"{idea_id:04d}-{slugify(idea['title'])}.{ext}"
    file_path.write_text(content)

    status = "draft" if idea["format"] in DRAFT_ONLY_FORMATS else "ready"
    ts = now_iso()
    cur.execute(
        """INSERT INTO products (idea_id, title, format, file_path, status, created_at)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (idea_id, idea["title"], idea["format"], str(file_path.relative_to(OUT_DIR.parent.parent.parent)), status, ts),
    )
    product_id = cur.lastrowid
    cur.execute("UPDATE product_ideas SET status = 'built' WHERE id = ?", (idea_id,))
    conn.commit()
    conn.close()
    return {"product_id": product_id, "file_path": str(file_path), "status": status}


def run(run_id: Optional[int] = None, limit: int = 12) -> list[dict]:
    init_db()
    conn = get_connection()
    query = "SELECT id FROM product_ideas WHERE status = 'proposed'"
    params: tuple = ()
    if run_id is not None:
        query += " AND run_id = ?"
        params = (run_id,)
    query += " ORDER BY demand_score DESC LIMIT ?"
    params = params + (limit,)
    idea_ids = [r["id"] for r in conn.execute(query, params).fetchall()]
    conn.close()

    built = []
    for idea_id in idea_ids:
        result = build_idea(idea_id)
        if result:
            built.append(result)
    print(f"[content_agent] built={len(built)} products "
          f"(ready={sum(1 for b in built if b['status'] == 'ready')}, "
          f"draft={sum(1 for b in built if b['status'] == 'draft')})")
    return built


if __name__ == "__main__":
    run_id_arg = int(sys.argv[1]) if len(sys.argv) > 1 else None
    run(run_id_arg)
