"""Landing Page Agent.

Turns each `products` row with status='ready' into an actual static HTML
page under `site/`, and registers it in `pages`. Draft-status products
(ebook/sop outlines - see content_agent.py) are skipped: publishing a
skeleton as if it were a finished landing page would misrepresent it.

Per-format rendering:
  - calculator: the generated tool *is* the page - copied as-is into
    site/products/, with a short intro paragraph injected above the tool.
  - checklist / prompt_pack (Markdown): rendered with a small built-in
    Markdown-subset renderer (headings, checklist items, blockquotes,
    paragraphs, hr) into the page body, plus a download link to the raw file.
  - template (CSV): rendered as an HTML preview table, plus a download link.

If `products.monetization_url` is set (e.g. a Gumroad listing - set
manually once the user creates one, this system doesn't create payment
accounts on anyone's behalf), the download link is replaced with a link to
that listing and the file is *not* also copied into site/downloads/ - no
point undermining a paid listing by giving the same file away for free
next to it.
"""
import csv
import html
import io
import re
import shutil
import sys
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agents.common import markdown_lite_to_html, now_iso, slugify
from agents.pdf_export import export as export_pdf
from core.db import get_connection, init_db

ROOT = Path(__file__).resolve().parent.parent
SITE_DIR = ROOT / "site"
PAGES_DIR = SITE_DIR / "products"
DOWNLOADS_DIR = SITE_DIR / "downloads"

PAGE_CSS = """
  :root { color-scheme: light dark; }
  body { font-family: -apple-system, system-ui, sans-serif; max-width: 720px;
         margin: 0 auto; padding: 2rem 1.25rem 4rem; color: #1a1a1a; background: #ffffff; }
  h1 { font-size: 1.8rem; margin-bottom: 0.25rem; }
  .subtitle { color: #555; margin-top: 0; }
  .card { background: #f6f6f6; border-radius: 10px; padding: 1.25rem 1.5rem; margin: 1.5rem 0; }
  a.button { display: inline-block; background: #1a1a1a; color: #fff; padding: 0.6rem 1.2rem;
             border-radius: 6px; text-decoration: none; font-weight: 600; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #ddd; padding: 0.5rem; text-align: left; font-size: 0.9rem; }
  th { background: #f0f0f0; }
  blockquote { background: #f6f6f6; border-left: 3px solid #999; margin: 0.75rem 0;
               padding: 0.5rem 1rem; }
  footer { margin-top: 2.5rem; font-size: 0.8rem; color: #888; }
"""


def page_shell(title: str, meta_description: str, body_html: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{html.escape(title)}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{html.escape(meta_description)}">
<style>{PAGE_CSS}</style>
</head>
<body>
{body_html}
<footer>Generated by the Biznis pipeline. <a href="../index.html">Back to all products</a></footer>
</body>
</html>
"""


def csv_to_html_table(csv_text: str, max_rows: int = 10) -> str:
    reader = csv.reader(io.StringIO(csv_text))
    rows = list(reader)
    if not rows:
        return "<p><em>Empty template.</em></p>"
    header, *body = rows
    out = ["<table>", "<tr>" + "".join(f"<th>{html.escape(c)}</th>" for c in header) + "</tr>"]
    for row in body[:max_rows]:
        out.append("<tr>" + "".join(f"<td>{html.escape(str(c))}</td>" for c in row) + "</tr>")
    out.append("</table>")
    return "\n".join(out)


def inject_intro_into_calculator(html_text: str, intro_html: str, meta_description: str) -> str:
    """Insert the intro right after the tool's own <h1> (not right after
    <body> - that would render the subtitle above the title), add a meta
    description, and append the same footer nav every other page gets."""
    h1_match = re.compile(r"</h1>", re.IGNORECASE).search(html_text)
    if h1_match:
        insert_at = h1_match.end()
        html_text = html_text[:insert_at] + "\n" + intro_html + html_text[insert_at:]

    head_match = re.compile(r"</head>", re.IGNORECASE).search(html_text)
    if head_match:
        meta_tag = f'<meta name="description" content="{html.escape(meta_description)}">\n'
        html_text = html_text[:head_match.start()] + meta_tag + html_text[head_match.start():]

    footer = '<footer>Generated by the Biznis pipeline. <a href="../index.html">Back to all products</a></footer>\n'
    body_close = re.compile(r"</body>", re.IGNORECASE).search(html_text)
    if body_close:
        html_text = html_text[:body_close.start()] + footer + html_text[body_close.start():]

    return html_text


def blurb_for(term: str, format_: str, rationale: str, monetized: bool) -> str:
    lead = "Paid" if monetized else "Free"
    return f"{lead} {format_.replace('_', ' ')} for \"{term}\", generated from real demand signals: {rationale}"


def build_page(product: dict) -> Optional[dict]:
    title = product["title"]
    fmt = product["format"]
    term = product["term"]
    rationale = product["rationale"] or ""
    monetization_url = product.get("monetization_url")
    src_path = ROOT / product["file_path"]
    if not src_path.exists():
        return None

    slug = slugify(title)
    meta_description = blurb_for(term, fmt, rationale, bool(monetization_url))[:160]
    intro_html = f'<p class="subtitle">{html.escape(rationale)}</p>'

    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    DOWNLOADS_DIR.mkdir(parents=True, exist_ok=True)

    if fmt == "calculator":
        raw = src_path.read_text()
        page_html = inject_intro_into_calculator(raw, intro_html, meta_description)
        page_path = PAGES_DIR / f"{slug}.html"
        page_path.write_text(page_html)
    else:
        raw = src_path.read_text()
        if fmt == "template":
            body = csv_to_html_table(raw)
        else:  # checklist, prompt_pack, ebook, sop
            body = markdown_lite_to_html(raw)

        if monetization_url:
            # Paid listing: don't also give the file away for free alongside it.
            cta = (f'<a class="button" href="{html.escape(monetization_url)}" '
                   f'target="_blank" rel="noopener">Get it on Gumroad</a>')
        else:
            if fmt in ("ebook", "sop"):
                # A raw .md isn't a great deliverable for a standalone
                # document (and some marketplaces won't even accept it as
                # an upload type) - a proper PDF is the better artifact.
                download_name = src_path.stem + ".pdf"
                export_pdf(src_path, DOWNLOADS_DIR / download_name)
            else:  # checklist, prompt_pack, template - fine as their native file
                download_name = src_path.name
                shutil.copyfile(src_path, DOWNLOADS_DIR / download_name)
            cta = (f'<a class="button" href="../downloads/{html.escape(download_name)}" '
                   f'download>Download {html.escape(fmt)}</a>')

        body_html = (f"<h1>{html.escape(title)}</h1>\n{intro_html}\n"
                     f'<div class="card">{body}</div>\n{cta}')
        page_path = PAGES_DIR / f"{slug}.html"
        page_path.write_text(page_shell(title, meta_description, body_html))

    return {
        "url": str(page_path.relative_to(SITE_DIR)),
        "title": title,
        "meta_description": meta_description,
    }


def build_index(pages: list[dict]) -> None:
    items = "\n".join(
        f'<li><a href="products/{Path(p["url"]).name}">{html.escape(p["title"])}</a>'
        f'<div class="subtitle">{html.escape(p["meta_description"])}</div></li>'
        for p in pages
    )
    body = f"""<h1>Biznis - Free Digital Products</h1>
<p class="subtitle">Generated from real, live demand signals - see the project repo for how.</p>
<ul>{items}</ul>"""
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    (SITE_DIR / "index.html").write_text(page_shell(
        "Biznis - Free Digital Products",
        "Free checklists, templates, calculators and prompt packs generated from real demand signals.",
        body,
    ))


def run(run_id: Optional[int] = None) -> list[int]:
    init_db()
    conn = get_connection()
    cur = conn.cursor()

    query = """SELECT p.id AS product_id, p.title, p.format, p.file_path,
                      p.monetization_url, pi.rationale, k.term
               FROM products p
               JOIN product_ideas pi ON pi.id = p.idea_id
               JOIN keywords k ON k.id = pi.target_keyword_id
               LEFT JOIN pages pg ON pg.product_id = p.id
               WHERE p.status = 'ready' AND pg.id IS NULL"""
    to_build = cur.execute(query).fetchall()

    ts = now_iso()
    new_page_ids = []
    for row in to_build:
        try:
            result = build_page(dict(row))
        except Exception as exc:  # e.g. Chrome missing for a PDF export - don't take the whole run down
            print(f"[landing_page_agent] failed to build page for product_id={row['product_id']}: {exc}")
            continue
        if not result:
            continue
        cur.execute(
            """INSERT INTO pages (product_id, url, title, meta_description, status, created_at)
               VALUES (?, ?, ?, ?, 'draft', ?)""",
            (row["product_id"], result["url"], result["title"], result["meta_description"], ts),
        )
        new_page_ids.append(cur.lastrowid)
    conn.commit()

    all_pages = cur.execute("SELECT url, title, meta_description FROM pages ORDER BY id").fetchall()
    conn.close()
    build_index([dict(p) for p in all_pages])

    print(f"[landing_page_agent] built {len(new_page_ids)} new pages "
          f"({len(all_pages)} total in site/)")
    return new_page_ids


if __name__ == "__main__":
    run_id_arg = int(sys.argv[1]) if len(sys.argv) > 1 else None
    run(run_id_arg)
