"""Landing Page Agent.

Turns each `products` row with status='ready' into an actual static HTML
page under `site/`, and registers it in `pages`. Draft-status products
(ebook/sop outlines - see content_agent.py) are skipped: publishing a
skeleton as if it were a finished landing page would misrepresent it.

Per-format rendering:
  - calculator: the generated tool *is* the page - copied as-is into
    site/products/, with a short intro paragraph injected above the tool.
  - checklist / prompt_pack (Markdown): rendered with a small built-in
    Markdown-subset renderer (headings, checklist items, blockquotes,
    paragraphs, hr) into the page body, plus a download link to the raw file.
  - template (CSV): rendered as an HTML preview table, plus a download link.

If `products.monetization_url` is set (e.g. a Gumroad listing - set
manually once the user creates one, this system doesn't create payment
accounts on anyone's behalf), the download link is replaced with a link to
that listing and the file is *not* also copied into site/downloads/ - no
point undermining a paid listing by giving the same file away for free
next to it.
"""
import csv
import html
import io
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agents.common import (CONTACT_EMAIL, FAVICON_DATA_URI, SITE_CSS, format_badge_html,
                            markdown_lite_to_html, marketing_blurb, now_iso, site_header_html, slugify)
from agents.pdf_export import export as export_pdf
from core.db import get_connection, init_db

ROOT = Path(__file__).resolve().parent.parent
SITE_DIR = ROOT / "site"
PAGES_DIR = SITE_DIR / "products"
DOWNLOADS_DIR = SITE_DIR / "downloads"

# Set once the user creates a Google Search Console property for this site
# and chooses the HTML-tag verification method - without this, Google may
# not discover/index the site at all for a long time.
GOOGLE_SITE_VERIFICATION = os.environ.get("GOOGLE_SITE_VERIFICATION", "")

# Set once the user creates a free Formspree form and gives us its endpoint
# (https://formspree.io/f/XXXXXXXX) - lets "service" pages use a real
# contact form that forwards to the site owner's email without ever
# putting that email address in the page source. Falls back to a mailto
# CTA (which *does* expose the address) until this is configured.
FORMSPREE_ENDPOINT = os.environ.get("FORMSPREE_ENDPOINT", "")

# Same var seo_agent.py uses. Needed here too because the homepage
# (index.html) is built directly by this module and never passes through
# seo_agent.py's post-hoc inject() (that only processes rows in the
# `pages` table, one per product - the homepage isn't a "product"). Found
# via a crawl-readiness audit: every product page had a canonical link,
# the homepage - the single most important URL on the whole site - had
# none at all.
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "").rstrip("/")

# Human-readable download-button labels - fmt.replace("_", " ") alone would
# still read as internal jargon for some formats ("swipe file" isn't a term
# most visitors recognize; found this after "Download swipe_file" - with
# the underscore visible - shipped to production).
DOWNLOAD_LABEL_BY_FORMAT = {
    "swipe_file": "scripts",
    "prompt_pack": "prompts",
}

def page_shell(title: str, meta_description: str, body_html: str, is_index: bool = False) -> str:
    verification_tag = (
        f'<meta name="google-site-verification" content="{html.escape(GOOGLE_SITE_VERIFICATION)}">\n'
        if GOOGLE_SITE_VERIFICATION else ""
    )
    main_class = ' class="wide"' if is_index else ""
    # The homepage doesn't go through seo_agent.py's per-product inject()
    # step, so it's the only page that needs its canonical/OG tags added
    # right here rather than post-hoc.
    index_seo_tags = ""
    if is_index and SITE_BASE_URL:
        index_seo_tags = (
            f'<link rel="canonical" href="{SITE_BASE_URL}/">\n'
            f'<meta property="og:title" content="{html.escape(title)}">\n'
            f'<meta property="og:description" content="{html.escape(meta_description)}">\n'
            f'<meta property="og:url" content="{SITE_BASE_URL}/">\n'
            f'<meta property="og:type" content="website">\n'
        )
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{html.escape(title)}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{html.escape(meta_description)}">
<link rel="icon" href="{FAVICON_DATA_URI}">
{verification_tag}{index_seo_tags}<style>{SITE_CSS}</style>
</head>
<body>
{site_header_html(active_is_index=is_index)}
<main{main_class}>
{body_html}
</main>
<footer>Generated by the Biznis pipeline from real demand signals.
<a href="{'index.html' if is_index else '../index.html'}">Back to all products</a></footer>
</body>
</html>
"""


def csv_to_html_table(csv_text: str, max_rows: int = 10) -> str:
    reader = csv.reader(io.StringIO(csv_text))
    rows = list(reader)
    if not rows:
        return "<p><em>Empty template.</em></p>"
    header, *body = rows
    out = ["<table>", "<tr>" + "".join(f"<th>{html.escape(c)}</th>" for c in header) + "</tr>"]
    for row in body[:max_rows]:
        out.append("<tr>" + "".join(f"<td>{html.escape(str(c))}</td>" for c in row) + "</tr>")
    out.append("</table>")
    return "\n".join(out)


def inject_intro_into_calculator(html_text: str, intro_html: str, meta_description: str, fmt: str) -> str:
    """Insert the format badge + intro right after the tool's own <h1> (not
    right after <body> - that would render the subtitle above the title),
    add a meta description + favicon, the shared site header right after
    <body>, and the same footer nav every other page gets."""
    h1_match = re.compile(r"<h1>", re.IGNORECASE).search(html_text)
    if h1_match:
        insert_at = h1_match.start()
        html_text = html_text[:insert_at] + format_badge_html(fmt) + "\n" + html_text[insert_at:]
    h1_close_match = re.compile(r"</h1>", re.IGNORECASE).search(html_text)
    if h1_close_match:
        insert_at = h1_close_match.end()
        html_text = html_text[:insert_at] + "\n" + intro_html + html_text[insert_at:]

    head_match = re.compile(r"</head>", re.IGNORECASE).search(html_text)
    if head_match:
        meta_tag = (f'<meta name="description" content="{html.escape(meta_description)}">\n'
                    f'<link rel="icon" href="{FAVICON_DATA_URI}">\n')
        html_text = html_text[:head_match.start()] + meta_tag + html_text[head_match.start():]

    body_match = re.compile(r"<body>", re.IGNORECASE).search(html_text)
    if body_match:
        insert_at = body_match.end()
        html_text = html_text[:insert_at] + "\n" + site_header_html() + html_text[insert_at:]

    footer = ('<footer>Generated by the Biznis pipeline from real demand signals. '
              '<a href="../index.html">Back to all products</a></footer>\n')
    body_close = re.compile(r"</body>", re.IGNORECASE).search(html_text)
    if body_close:
        html_text = html_text[:body_close.start()] + footer + html_text[body_close.start():]

    return html_text


def contact_form_html() -> str:
    """A real contact form posting straight to Formspree - no email address
    anywhere in this page's source. The honeypot ("_gotcha") is Formspree's
    own spam-trap convention: a field hidden from real visitors via CSS
    that, if filled in, means a bot filled out every field blindly."""
    return f"""<form class="contact-form" action="{html.escape(FORMSPREE_ENDPOINT)}" method="POST">
<label for="name">Name</label>
<input type="text" id="name" name="name" required>
<label for="email">Your email</label>
<input type="email" id="email" name="email" required>
<label for="message">What do you need?</label>
<textarea id="message" name="message" required></textarea>
<input type="text" name="_gotcha" style="display:none" tabindex="-1" autocomplete="off">
<button type="submit" class="button">Send</button>
<p class="form-note">Goes straight to us - no account or signup needed on your end.</p>
</form>"""


def build_page(product: dict) -> Optional[dict]:
    title = product["title"]
    fmt = product["format"]
    term = product["term"]
    monetization_url = product.get("monetization_url")
    src_path = ROOT / product["file_path"]
    if not src_path.exists():
        return None

    slug = slugify(title)
    meta_description = marketing_blurb(term, fmt, bool(monetization_url))[:160]
    intro_html = f'<p class="subtitle">{html.escape(meta_description)}</p>'

    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    DOWNLOADS_DIR.mkdir(parents=True, exist_ok=True)

    if fmt == "calculator":
        raw = src_path.read_text()
        page_html = inject_intro_into_calculator(raw, intro_html, meta_description, fmt)
        page_path = PAGES_DIR / f"{slug}.html"
        page_path.write_text(page_html)
    else:
        raw = src_path.read_text()
        if fmt == "template":
            body = csv_to_html_table(raw)
        else:  # checklist, prompt_pack, ebook, sop
            # Every generator's file starts with "# {title}" as its own
            # standalone document title - redundant with the page's own
            # <h1> shown just above this card, so drop that one line here.
            content_lines = raw.splitlines()
            if content_lines and content_lines[0].strip().startswith("# "):
                raw = "\n".join(content_lines[1:])
            body = markdown_lite_to_html(raw)

        if fmt == "service":
            # Not a download - a custom-scoped offering, so the CTA is a
            # contact method instead of a file. Prefer the real contact
            # form (email address never appears in the page source) once
            # Formspree is configured; fall back to mailto (which *does*
            # expose the address) until then.
            cta = contact_form_html() if FORMSPREE_ENDPOINT else (
                f'<a class="button" href="mailto:{CONTACT_EMAIL}">Get in touch</a>')
        elif monetization_url:
            # Paid listing: don't also give the file away for free alongside it.
            cta = (f'<a class="button" href="{html.escape(monetization_url)}" '
                   f'target="_blank" rel="noopener">Get it on Gumroad</a>')
        else:
            if fmt in ("ebook", "sop"):
                # A raw .md isn't a great deliverable for a standalone
                # document (and some marketplaces won't even accept it as
                # an upload type) - a proper PDF is the better artifact.
                download_name = src_path.stem + ".pdf"
                export_pdf(src_path, DOWNLOADS_DIR / download_name, title=title)
            else:  # checklist, prompt_pack, template - fine as their native file
                download_name = src_path.name
                shutil.copyfile(src_path, DOWNLOADS_DIR / download_name)
            label = DOWNLOAD_LABEL_BY_FORMAT.get(fmt, fmt.replace("_", " "))
            cta = (f'<a class="button" href="../downloads/{html.escape(download_name)}" '
                   f'download>Download {html.escape(label)}</a>')

        body_html = (f"{format_badge_html(fmt)}\n<h1>{html.escape(title)}</h1>\n{intro_html}\n"
                     f'<div class="card">{body}</div>\n{cta}')
        page_path = PAGES_DIR / f"{slug}.html"
        page_path.write_text(page_shell(title, meta_description, body_html))

    return {
        "url": str(page_path.relative_to(SITE_DIR)),
        "title": title,
        "meta_description": meta_description,
    }


def build_index(pages: list[dict]) -> None:
    services = [p for p in pages if p["format"] == "service"]
    products = [p for p in pages if p["format"] != "service"]

    service_cards = "\n".join(
        f'<a class="service-card" href="products/{Path(p["url"]).name}">'
        f'{format_badge_html(p["format"])}'
        f'<h3>{html.escape(p["title"])}</h3>'
        f'<p>{html.escape(p["meta_description"])}</p></a>'
        for p in services
    )
    product_cards = "\n".join(
        f'<a class="product-card" href="products/{Path(p["url"]).name}">'
        f'{format_badge_html(p["format"])}'
        f'<h3>{html.escape(p["title"])}</h3>'
        f'<p>{html.escape(p["meta_description"])}</p></a>'
        for p in products
    )
    services_section = (
        f'<h2 id="services" class="section-title">Work with us</h2>\n'
        f'<div class="service-grid">{service_cards}</div>\n'
        if services else ""
    )
    body = f"""<div class="hero">
<h1>Biznis</h1>
<p class="subtitle">Free digital products - checklists, templates, calculators, and ready-to-send
scripts - built from real, live demand signals. Plus custom website and chatbot development.
See the project repo for how the products are made.</p>
</div>
{services_section}
<h2 class="section-title">Free products</h2>
<div class="product-grid">{product_cards}</div>"""
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    (SITE_DIR / "index.html").write_text(page_shell(
        "Biznis - Free Digital Products & Custom Development",
        "Free checklists, templates, calculators and prompt packs generated from real demand "
        "signals, plus custom website and chatbot development.",
        body,
        is_index=True,
    ))


def run(run_id: Optional[int] = None) -> list[int]:
    init_db()
    conn = get_connection()
    cur = conn.cursor()

    query = """SELECT p.id AS product_id, p.title, p.format, p.file_path,
                      p.monetization_url, k.term
               FROM products p
               JOIN product_ideas pi ON pi.id = p.idea_id
               JOIN keywords k ON k.id = pi.target_keyword_id
               LEFT JOIN pages pg ON pg.product_id = p.id
               WHERE p.status = 'ready' AND pg.id IS NULL"""
    to_build = cur.execute(query).fetchall()

    ts = now_iso()
    new_page_ids = []
    for row in to_build:
        try:
            result = build_page(dict(row))
        except Exception as exc:  # e.g. Chrome missing for a PDF export - don't take the whole run down
            print(f"[landing_page_agent] failed to build page for product_id={row['product_id']}: {exc}")
            continue
        if not result:
            continue
        cur.execute(
            """INSERT INTO pages (product_id, url, title, meta_description, status, created_at)
               VALUES (?, ?, ?, ?, 'draft', ?)""",
            (row["product_id"], result["url"], result["title"], result["meta_description"], ts),
        )
        new_page_ids.append(cur.lastrowid)
    conn.commit()

    all_pages = cur.execute(
        """SELECT pg.url, pg.title, pg.meta_description, p.format
           FROM pages pg JOIN products p ON p.id = pg.product_id
           ORDER BY pg.id"""
    ).fetchall()
    conn.close()
    build_index([dict(p) for p in all_pages])

    print(f"[landing_page_agent] built {len(new_page_ids)} new pages "
          f"({len(all_pages)} total in site/)")
    return new_page_ids


if __name__ == "__main__":
    run_id_arg = int(sys.argv[1]) if len(sys.argv) > 1 else None
    run(run_id_arg)
