"""Markdown -> PDF export, shared by landing_page_agent.py (ebook/sop
downloads) and scripts/export_pdf.py (manual CLI use, e.g. producing a file
to upload to a marketplace that won't accept .md).

Reuses the same Markdown-lite renderer as the web pages (agents.common.
markdown_lite_to_html) so the PDF and the HTML page never drift into two
different parsers, then shells out to headless Chrome's built-in
--print-to-pdf, since no PDF library is installed and Chrome is already
present on this machine.
"""
import os
import re
import subprocess
import tempfile
from pathlib import Path

from agents.common import markdown_lite_to_html

CHROME_PATHS = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/usr/bin/google-chrome",
    "/usr/bin/google-chrome-stable",
    "/usr/bin/chromium-browser",
    "/usr/bin/chromium",
]

PRINT_CSS = """
  body { font-family: Georgia, 'Times New Roman', serif; max-width: 640px;
         margin: 0 auto; padding: 1rem; color: #1a1a1a; line-height: 1.55; }
  h1 { font-size: 1.9rem; margin-top: 0; }
  h2 { font-size: 1.3rem; margin-top: 2rem; border-top: 1px solid #ddd; padding-top: 1rem; }
  h3 { font-size: 1.1rem; }
  blockquote { border-left: 3px solid #999; margin: 1rem 0; padding: 0.25rem 1rem;
               color: #444; font-style: italic; }
  ul { padding-left: 1.2rem; }
  li { margin-bottom: 0.5rem; }
  .credit { margin-top: 3rem; font-size: 0.8rem; color: #888; border-top: 1px solid #ddd;
            padding-top: 1rem; }
"""


def find_chrome() -> str:
    env_path = os.environ.get("CHROME_PATH")  # set by browser-actions/setup-chrome in CI
    if env_path and Path(env_path).exists():
        return env_path
    for path in CHROME_PATHS:
        if Path(path).exists():
            return path
    raise FileNotFoundError("No Chrome/Chromium binary found - install one, set CHROME_PATH, "
                             "or add its path to CHROME_PATHS")


def title_from_stem(stem: str) -> str:
    stem = re.sub(r"^\d+-", "", stem)  # strip a leading "0003-" id prefix
    return stem.replace("-", " ").replace("_", " ").title()


def render_html(md_text: str, title: str) -> str:
    body = markdown_lite_to_html(md_text)
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>{title}</title>
<style>{PRINT_CSS}</style></head>
<body>
{body}
<p class="credit">Generated by the Biznis pipeline from real demand signals.</p>
</body></html>
"""


def export(md_path: Path, out_path: Path) -> None:
    title = title_from_stem(md_path.stem)
    html_text = render_html(md_path.read_text(), title)

    with tempfile.NamedTemporaryFile(mode="w", suffix=".html", delete=False) as f:
        f.write(html_text)
        tmp_html = f.name

    chrome = find_chrome()
    subprocess.run([
        chrome, "--headless", "--disable-gpu", "--no-sandbox",
        f"--print-to-pdf={out_path}", "--no-pdf-header-footer",
        f"file://{tmp_html}",
    ], check=True, capture_output=True)

    Path(tmp_html).unlink()
    if not out_path.exists() or out_path.stat().st_size == 0:
        raise RuntimeError(f"PDF export failed - {out_path} is missing or empty")
